"""核心模块 - 配置、类型定义、相似度计算"""

from nallm.core.config import (
    __version__,
    ORG_SIM_THRESHOLD,
    P1_STRONG_TITLE_SIM,
    P1_STRONG_COAUTHOR,
    P1_HIGH_TITLE_SIM,
    P1_HIGH_COAUTHOR,
    P1_MEDIUM_TITLE_SIM,
    P0_HIGH_TITLE_SIM,
    P0_MEDIUM_TITLE_SIM,
    P0_HIGH_TOP5_AVG,
    P0_MEDIUM_TOP5_AVG,
    P0_HIGH_ORG_SIM,
    P0_HIGH_VENUE_SIM,
    COMP_ORG_SIM_THRESHOLD,
    COMP_VENUE_SIM_THRESHOLD,
    PUB_ORG_SIM_THRESHOLD,
    PUB_VENUE_SIM_THRESHOLD,
    ORG_MAX_LENGTH,
    MAX_TEXT_LENGTH,
    EMBEDDING_DIM,
    EMBEDDING_BATCH_SIZE,
    EMBEDDING_MODEL,
    EMBEDDING_API_BASE,
    DATA_DIR,
    EMBEDDING_DB_DIR,
    RESULTS_DIR,
    LOGS_DIR,
    SINGLE_NAME_PARTS,
)
from nallm.core.similarity import (
    set_org_embedding_getter,
    get_org_embedding,
    compute_org_similarity,
)

__all__ = [
    "__version__",
    "ORG_SIM_THRESHOLD",
    "P1_STRONG_TITLE_SIM",
    "P1_STRONG_COAUTHOR",
    "P1_HIGH_TITLE_SIM",
    "P1_HIGH_COAUTHOR",
    "P1_MEDIUM_TITLE_SIM",
    "P0_HIGH_TITLE_SIM",
    "P0_MEDIUM_TITLE_SIM",
    "P0_HIGH_TOP5_AVG",
    "P0_MEDIUM_TOP5_AVG",
    "P0_HIGH_ORG_SIM",
    "P0_HIGH_VENUE_SIM",
    "COMP_ORG_SIM_THRESHOLD",
    "COMP_VENUE_SIM_THRESHOLD",
    "PUB_ORG_SIM_THRESHOLD",
    "PUB_VENUE_SIM_THRESHOLD",
    "ORG_MAX_LENGTH",
    "MAX_TEXT_LENGTH",
    "EMBEDDING_DIM",
    "EMBEDDING_BATCH_SIZE",
    "EMBEDDING_MODEL",
    "EMBEDDING_API_BASE",
    "DATA_DIR",
    "EMBEDDING_DB_DIR",
    "RESULTS_DIR",
    "LOGS_DIR",
    "SINGLE_NAME_PARTS",
    # similarity
    "set_org_embedding_getter",
    "get_org_embedding",
    "compute_org_similarity",
]
